module.exports = {
  KeyChain: require('./lib/keychain'),
  BitcoreWallet: require('./lib/bitcore/bitcorewallet'),
  BlockCypherProvider: require('./lib/providers/blockcypherprovider'),
  InsightProvider: require('./lib/providers/insightprovider'),
  BCHInsightProvider: require('./lib/providers/bchinsightprovider'),
  LTCInsightProvider: require('./lib/providers/ltcinsightprovider'),
  BlockchainInfoProvider: require('./lib/providers/blockchaininfoprovider'),
  Utils: require('./lib/utils'),
  CompoundKey: require('./lib/compoundkey'),
  BitcoreTransaction: require('./lib/bitcore/bitcoretransaction'),
  BitcoinCashTransaction: require('./lib/bitcore/bitcoincashtransaction'),
  LitecoinTransaction: require('./lib/bitcore/litecointransaction'),
  BitcoinTransaction: require('./lib/bitcore/bitcointransaction'),
  EthereumTransaction: require('./lib/ethereum/ethereumtransaction'),
  SchnorrProof: require('./lib/schnorrproof'),
  PaillierProver: require('./lib/paillierprover'),
  PaillierVerifier: require('./lib/paillierverifier'),
  PedersenScheme: require('./lib/pedersenscheme'),
  DDS: require('./lib/dds'),
  EthereumWallet: require('./lib/ethereum/ethereumwallet'),
  ERC20Wallet: require('./lib/ethereum/erc20wallet'),
  Signer: require('./lib/signer'),
  Marshal: require('./lib/marshal')
};
